<script type="text/javascript">
$(document).ready(function() {
        $("#formLogin").validate();
});
</script>

<style type="text/css">
#formLogin { width: 500px; }
#formLogin label { width: 110px; }
#formLogin label.error { color: red;
                           margin-left: 30px;
                           width: auto;                          
                            } 
#formLogin input.submit{ margin-left: 353px; }


</style>
<form class="cmxform" id="formLogin" method="post" action="/admin/">
    <table border="0" cellpadding="0" cellspacing="0">
    <tr>
            <th>Username</th>
            <td><?php echo $this->element->Login;?></td>
    </tr>
    <tr>
            <th>Password</th>
            <td><?php echo $this->element->Password;?></td>
    </tr>
    <tr>
            <th></th>
    </tr>
    <tr>
            <th></th>
            <td><input type="submit"  class="submit-login" value="Iniciar Sesion"/></td>
    </tr>
    </table>
</form>