<ul class="breadcrumb">    
    <li>
        <a href="/user">Usuarios</a> <span class="divider">/</span>
    </li>    
</ul>
<div id="content_wrapper">
     <div id="content">
         <div class="inner">
             <form action="" method="post" enctype="multipart/form-data" class="well">
                <div class="header">
                    <h3>Registrar Usuario</h3>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <label for="nombre" class="span5 no-margin">Nombre :</label>
                        <div class="span4 no-margin">
                            <?php echo $this->form->nombreUsuario->setAttrib('class', 'span12')->setAttrib('maxlength', '50')->renderViewHelper();?>
                            <?php if ($this->form->nombreUsuario->hasErrors()) echo "Ingresa Nombre válido";?>
                        </div>
                        <div class="clear"></div>
                        <label for="apellido" class="span5 no-margin">Apellidos :</label>
                        <div class="span4 no-margin">
                            <?php echo $this->form->apellidoUsuario->setAttrib('class', 'span12')->setAttrib('maxlength', '50')->renderViewHelper();?>
                            <?php if ($this->form->apellidoUsuario->hasErrors()) echo "Ingresa Apellido";?>
                        </div>
                        <div class="clear"></div>
                        <label for="dni" class="span5 no-margin">Usuario :</label>
                        <div class="span4 no-margin">
                            <?php echo $this->form->usuario->setAttrib('class', 'span12')->setAttrib('maxlength', '8')->renderViewHelper();?>
                            <?php if ($this->form->usuario->hasErrors()) echo "Ingresa Usuario";?>
                        </div>
                        <div class="clear"></div>
                        <label for="fechaN" class="span5 no-margin">Clave:</label>
                        <div class="span4 no-margin">
                            <?php echo $this->form->clave->setAttrib('class', 'span12')->setAttrib('maxlength', '30')->renderViewHelper();?>
                            <?php if ($this->form->clave->hasErrors()) echo "Ingresa Password";?>
                        </div>
                        <div class="clear"></div>
                        <label for="email" class="span5 no-margin">Tipo Usuario:</label>
                        <div class="span4 no-margin">
                            <?php echo $this->form->tipoUsuario->setAttrib('class', 'span12')->setAttrib('maxlength', '50')->renderViewHelper();?>
                            
                        </div>
                        
                        <?php echo $this->form->csrf; ?>
                    </div>
                    <div class="clear"></div>
                                        
                </div>
                <div class="form-actions">
                    <?php echo $this->form->guardar->setAttrib('class', 'btn pull-right')?>                    
                </div>
        </form>
    </div>
 </div>
</div>
