  <div>
        <!-- row of columns -->
        <div class="row-fluid">
          
          <div>
                <ul class="breadcrumb">                    
                    <li><a href="/usuario/crear">Agregar Usuario</a></li>
                </ul>
              <form class="well inline" method="post" enctype="multipart/form-data" >
                      <h3>Buscar Clientes</h3>
                      <hr>                      
                      <div class="row-fluid">
                          <div class="span2">
                              <h4>Cod. Usuario</h4>
                              <?php echo $this->form->idUsuario;?>
                           </div>
                          <div class="span3">
                              <h4>Nombre</h4>
                              <?php echo $this->form->nombreUsuario;?>
                           </div>
                          <div class="span3">
                              <h4>Usuario</h4>
                              <?php echo $this->form->usuario;?>
                           </div>                          
                          <div class="span3">
                              <?php echo $this->form->buscar?>
                           </div>
                      </div>
                 </form>
                 <div id="message"></div>
                 <table class="table table-bordered">                     
                   <thead>
                     <tr>                       
                       <th>
                           Nombre
                       </th>
                       <th>
                           Apellido
                       </th>
                       <th>
                           Número de Visitas
                       </th>
                       <th>
                           Última visita
                       </th>
                       <th>                          
                          Teléfono
                       </th>
                       <th>                          
                          Email
                       </th>
                       <th>
                          Acciones
                       </th>
                     </tr>
                   </thead>
                   <tbody>
                     <?php
                     foreach ($this->result as $res):?>
                     <tr>
                       <td>
                         <?php echo $res["nombreCliente"]; ?>
                       </td>
                       <td>
                         <?php echo $res["apellidoCliente"]; ?>
                       </td>
                       <td>
                         <?php echo $res["totalVisitas"]; ?>
                       </td>
                       <td>
                         <?php echo $res["fechaUltimaVisita"]; ?>
                       </td>
                       <td>
                         <?php echo $res["telefono"]; ?>
                       </td>
                       <td>
                         <?php echo $res["correo"]; ?>
                       </td>                       
                       <td>
                           <a href="/cliente/editar/id/<?php echo $res["idCliente"]; ?>" title="Editar">Editar</a> |
                           <a href="/cliente/eliminar/id/<?php echo $res["idCliente"]; ?>" title="Editar">Eliminar</a>
                       </td>
                     </tr>
                         <?php endforeach; ?>
                   </tbody>
                 </table>
         </div>
        </div>                
  </div>