  <div>
        <!-- row of columns -->
        <div class="row-fluid">
          
          <div>
                <ul class="breadcrumb">                    
                    <li><a href="#">Consultar reporte entre fechas</a></li>
                </ul>
              <form class="well inline" method="post" enctype="multipart/form-data" >
                      <h3>Buscar Tickets</h3>
                      <hr>                      
                      <div class="row-fluid">
                          <div class="span4">
                              <h4>Fecha Inicial:</h4>
                              <?php echo $this->form->fechaInicial;?>
                           </div>
                          <div class="span4">
                              <h4>Fecha Final:</h4>
                              <?php echo $this->form->fechaFinal;?>
                           </div>
                                    
                          <div class="span1">
                              <?php echo $this->form->buscar?>
                           </div>
                      </div>
                 </form>
                 <div id="message"></div>
                 
                 <?php
                 error_reporting(E_ERROR);
                 if($this->result !=""){
                 ?>
                 <table class="table table-bordered">                     
                   <thead>
                     <tr>                       
                       <th>
                           Nro. Ticket
                       </th>
                       <th>
                           Tipo Usuario
                       </th>
                       <th>
                           Nombre Usuario
                       </th>
                       <th>
                           Cliente
                       </th>
                       <th>
                           Fecha Creacion
                       </th>
                       <th>
                           Total
                       </th>
                       <th>
                           Accion
                       </th>
                       
                     </tr>
                   </thead>
                  <tbody>
                     <?php 
                     $total = "";
                     $igv ="";
                     $subTotal = "";
                     
                     foreach ($this->result as $res):
                     $total += $res["total"];    
                     
                     $igv = $total*0.18;
                     $subTotal = $total - $igv;
                     
                         
                         ?>
                     <tr>
                      <td>
                         <?php echo $res["idTicket"]; ?>
                       </td>
                       <td>
                         <?php echo $res["descripcion"]; ?>
                       </td>
                       <td>
                         <?php echo $res["nombreUsuario"]; ?>
                       </td>
                       <td>
                         <?php echo $res["nombreCliente"]; ?>
                       </td>
                       <td>
                         <?php echo $res["fechaCreacion"]; ?>
                       </td>
                       <td>
                         <?php echo $res["total"]; ?>
                       </td>
                       <td>
                         <a href="/admin/reporte/venta-diaria-detalle/id/<?php echo $res["idTicket"]; ?>" title="Detalle">Ver Detalle</a>
                       </td>
                      
                     </tr>
                         <?php endforeach; ?>
                     <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><span class="alert-info">Total S/.:</span> </td>
                        <td><?php echo $total;?></td>
                        <td></td>
                     </tr>
                     <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><span class="alert-info">IGV:</span> </td>
                        <td><?php echo round($igv,2);?></td>
                        <td></td>
                     </tr>
                     <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><span class="alert-info">Sub Total S/.:</span> </td>
                        <td><?php echo round($subTotal,2);?></td>
                        <td></td>
                     </tr>
                   </tbody>
                 </table>
                 <?php }?>
         </div>
        </div>                
  </div>
<script>
$(document).ready(function(){
    $('#fechaInicial').datepicker({
        format: 'yyyy-mm-dd',
        todayBtn: 'linked',
        language: 'es'
    });
    
     $('#fechaFinal').datepicker({
        format: 'yyyy-mm-dd',
        todayBtn: 'linked',
        language: 'es'
    });
});
</script>