  <div>
        <!-- row of columns -->
        <div class="row-fluid">
          
          <div>
                <ul class="breadcrumb">                    
                    <li><a href="#">Venta Diaria a la fecha <?php echo $this->fecha;?></a></li>
                </ul>
              
                 <div id="message"></div>
                 <table class="table table-bordered">                     
                   <thead>
                     <tr>                       
                       <th>
                           Nro. Ticket
                       </th>
                       <th>
                           Nombre Usuario
                       </th>
                       <th>
                           Efectivo
                       </th>
                       <th>
                           MasterCard
                       </th>
                       <th>
                           Visa
                       </th>
                       <th>
                           Total
                       </th>
                       <th>
                           Acciones
                       </th>
                       
                     </tr>
                   </thead>
                   <tbody>
                     <?php 
                     $total = "";
                     $totalEfectivo = "";
                     $totalMaster = "";
                     $totalVisa = "";
                     $igv ="";
                     $subTotal = "";
                     foreach ($this->ventaDiaria as $res):
                     $total += $res["total"];    
                     $totalEfectivo += $res["efectivo"];
                     $totalMaster += $res["mastercard"];
                     $totalVisa += $res["visa"];
                     
                     $igv = $total*0.18;
                     $subTotal = $total - $igv;
                     
                     ?>
                     <tr>
                      <td>
                         <?php echo $res["idTicket"]; ?>
                       </td>
                       <td>
                         <?php echo $res["nombreUsuario"]; ?>
                       </td>
                       <td>
                         <?php echo $res["efectivo"]; ?>
                       </td>
                       <td>
                         <?php echo $res["mastercard"]; ?>
                       </td>
                       <td>
                         <?php echo $res["visa"]; ?>
                       </td>
                       <td>
                         <?php echo $res["total"]; ?>
                       </td>
                       <td>
                           <a href="/admin/reporte/venta-diaria-detalle/id/<?php echo $res["idTicket"]; ?>" title="Detalle">Ver Detalle</a>
                       </td>
                     </tr>
                         <?php endforeach; ?>
                     <tr>
                        <td></td>
                        <td><span style="font-weight:bold">Total</span></td>
                        <td><span style="font-weight:bold"><?php echo $totalEfectivo;?></span> </td>
                        <td><span style="font-weight:bold"><?php echo $totalMaster;?></span> </td>
                        <td><span style="font-weight:bold"><?php echo $totalVisa;?></span> </td>
                        <td><span style="font-weight:bold"><?php echo $total;?></td></span> </td>
                        <td></td>
                     </tr>
                     
                     <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><span class="alert-info">IGV:</span> </td>
                        <td><?php echo round($igv,2);?></td>
                        <td></td>
                     </tr>
                     <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><span class="alert-info">Sub Total S/.:</span> </td>
                        <td><?php echo round($subTotal,2);?></td>
                        <td></td>
                     </tr>
                   </tbody>
                 </table>
         </div>
        </div>                
  </div>
