<div id="login-holder">

	<!-- start logo -->
	<div id="logo-login">
		<a href="index.html"><img src="../img/shared/logo1.png" width="156" height="40" alt="" /></a>
	</div>
	<!-- end logo -->
	
	<div class="clear"></div>
	
	<!--  start loginbox ................................................................................. -->
	<div id="loginbox">
	
	<!--  start login-inner -->
	<div id="login-inner">
            
            
            <script type="text/javascript">
                $(document).ready(function() {
                $("#formLogin").validate();
        });
        </script>

                <style type="text/css">
                #formLogin { width: 500px; }
                #formLogin label { width: 110px; }
                #formLogin label.error { color: red;
                                        margin-left: 30px;
                                        width: auto;                          
                                            } 
                #formLogin input.submit{ margin-left: 353px; }


                </style>
                <form class="cmxform" id="formLogin" method="post" action="/admin/auth/index/">
                    <table border="0" cellpadding="0" cellspacing="0">
                    <tr>
                            <th>Username</th>
                            <td><?php echo $this->formLogin->usuario;?></td>
                    </tr>
                    <tr>
                            <th>Password</th>
                            <td><?php echo $this->formLogin->pwd;?></td>
                    </tr>
                    <tr>
                            <th></th>
                    </tr>
                    <tr>
                            <th></th>
                            <td><input type="submit"  class="" value="Iniciar Sesion"/></td>
                    </tr>
                    </table>
                </form>
            
            
            
            
            
            
            
            
            
            
            
            
	</div>
 	<!--  end login-inner -->
	<div class="clear"></div>
	<a href="" class="forgot-pwd"></a>
 </div>
 <!--  end loginbox -->

</div>