<ul class="breadcrumb">
    <li>
        <a href="/producto">Listado Productos</a> <span class="divider">/</span>
    </li>
</ul>
<div id="content_wrapper">
     <div id="content">
         <div class="inner">
             <form action="" method="post" enctype="multipart/form-data" class="well">
                <div class="header">
                    <h3>Detalles del Producto</h3>
                </div>
                 </br>
                <div class="row-fluid">
                    <div class="span6">
                        <label for="nombre" class="span5 no-margin">Descripción Producto :</label>
                        <div class="span4 no-margin">
                            <?php echo $this->form->nombreProducto->setAttrib('class', 'span12')->setAttrib('maxlength', '50')->renderViewHelper();?>
                            <?php if ($this->form->nombreProducto->hasErrors()) echo "Ingresa Nombre válido";?>
                        </div>
                        <div class="clear"></div>
                        <label for="precio" class="span5 no-margin">Precio :</label>
                        <div class="span4 no-margin">                            
                            <?php echo $this->form->precio->setAttrib('class', 'span12')->renderViewHelper();?>
                            <?php if ($this->form->precio->hasErrors()) echo "Ingresa campo válido";?>
                            
                        </div>
                        <div class="clear"></div>
                        <label for="dni" class="span5 no-margin">Foto :</label>
                        <div class="span4 no-margin">                            
                            <?php 
                            if(isset ($this->producto['foto']) and !empty ($this->producto['foto'])) {
                                echo $this->producto['foto'];
                                ?> <a href="/producto/eliminarfoto/id/<?php echo $this->producto['idProducto']?>">Eliminar</a>                                    
                                <input type="hidden" id="foto" name="fotoAnt" value="<?php echo $this->producto['fotoAnt']?>"/>
                            <?php }else {
                            echo $this->form->foto;
                            if ($this->form->foto->hasErrors()) echo "Imagen inválida";
                            
                            }
                            ?>
                        </div>
                        <div class="clear"></div>                        
                        <?php echo $this->form->csrf; ?>
                        <?php if ($this->form->csrf->hasErrors()) echo "Intentalo nuevamente";?>
                    </div>
                    <div class="clear"></div>
                                        
                </div>
                <div class="form-actions">
                    <?php echo $this->form->guardar->setAttrib('class', 'btn pull-right')?>
                </div>
        </form>
    </div>
 </div>
</div>
