    <div>
        <div class="row-fluid">          
          <div>
                <ul class="breadcrumb">                    
                    <li><a href="/ticket/nuevo">Nuevo Ticket</a></li>
                </ul>
              <form class="well inline" method="post" enctype="multipart/form-data" >
                      <h3>Listado Tickets Atendidos por Usuario</h3>
                      <hr>                      
                      <div class="row-fluid">
                          <div class="span2">
                              <h4>Cod. Usuario</h4>
                              <?php echo $this->form->idUsuario?>
                           </div>
                          <div class="span3">
                              <h4>Nombre Usuario</h4>
                              <?php echo $this->form->nombre?>
                           </div>
                          <div class="span3">
                              <?php echo $this->form->buscar?>
                           </div>
                      </div>
                 </form>
                 <div id="message"></div>
                 <table class="table table-bordered">                     
                   <thead>
                     <tr>                                                
                       <th>
                           Cod.
                       </th>
                       <th>
                           Cliente
                       </th>
                       <th>
                           Fecha atención
                       </th>
                       <th>
                           Atendido por
                       </th>                       
                       <th>
                          Monto
                       </th>
                     </tr>
                   </thead>
                   <tbody>
                     <?php
                     foreach ($this->result as $res):?>
                     <tr>
                       <td>
                         <?php echo $res["idTicket"]; ?>
                       </td>
                       <td>
                         <?php echo $res["nombreCliente"] . " " . $res["apellidoCliente"]; ?>
                       </td>
                       <td>
                         <?php echo $res["fechaCreacion"]; ?>
                       </td>
                       <td>
                         <?php echo $res["nombreUsuario"] . " " . $res["apellidoUsuario"]; ?>
                       </td>                       
                       <td>
                           <?php echo $res["total"]; ?>
                       </td>
                     </tr>
                         <?php endforeach; ?>
                   </tbody>
                 </table>
         </div>
        </div>                
  </div>