<ul class="breadcrumb">    
    <li>
        <a href="/agenda">Ir Agenda</a> <span class="divider">/</span>
    </li>    
</ul>

<form class="form-horizontal" id="frmTicket" action="" method="post">

    <div class="control-group">
        <label class="control-label" for="inputName">Cliente : </label>
        <div class="controls">
            <input id="clienteReserva" data-provide="typeahead" type="text" id="input" class="span5" placeholder="Ingrese Cliente" value="<?php echo $this->nombreUser?>" required>
            <span class="help-inline">
                <a href="/cliente/crear" class="btn">
                    <span class="icon-plus"></span>
                </a>
            </span>
        </div>
    </div>
    <input type="hidden" value="" id="idCliente">
    <input type="hidden" value="<?php echo $this->idCliente?>" id="otroCliente" name="otroCliente" required>
    
    <input type="hidden" value="" id="idPrecio">
    
    <div class="control-group">
        <label class="control-label" for="inputServicio">Servicio : </label>
        <div class="controls">
            <select name ="idServicio" id="idServicio" class="span3">
                <option value="0">--Seleccionar--</option>
                <?php 
                $ser = $this->servicios;
                foreach ($ser as $item):
                ?>
                <option id="servicio" value="<?php echo $item['idServicio']?>" precio="<?php echo $item['precio']?>"> <?php echo $item['descripcionServicio']?></option>
                <?php endforeach; ?>
            </select>    
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputProducto">Producto : </label>
        <div class="controls">
            <select name ="idProducto" id="idProducto" class="span3">
                <option value="0">--Seleccionar--</option>
                <?php 
                $producto = $this->productos;
                foreach ($producto as $item):
                ?>
                <option id="servicio" value="<?php echo $item['idProducto']?>" precio="<?php echo $item['precio']?>"> <?php echo $item['nombreProducto']?></option>
                <?php endforeach; ?>
            </select>    
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputAtendido">Atendido por : </label>
        <div class="controls">
            <select class="xlarge disabled" id="idUsuario" name="idUsuario" disabled="disabled">
                    <option value="0">-- Seleccionar --</option>
                </select>                    
            <span class="help-inline">
                <a class="btn" id="agregarItem" disabled="disabled">
                    <span>Agregar Servicio</span>
                </a>
            </span>
        </div>
    </div>
    
    <br/>
    <br/>
    
    <div id="idPanelTablaDetalleIngreso">
                <table class="table table-condensed">
                    <caption class="alert">Servicios Brindados</caption>
                    <thead>
                        <tr>
                            <th>Servicio</th>
                            <th>Precio</th>
                            <th>Atendido por</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody class="">
                        <tr class="hide modelo">
                            
                            <th></th>
                            <th></th>
                            <th></th>
                            <th>
                                <a class="eliminarDetalleIngreso"> Eliminar</a>
                            </th>
                        </tr>                        
                    </tbody>
                </table>
        <input type="hidden" id="totalValue" name="totalValue" value=""/>
        <p>
            <strong> Total S/.<span id="totalfinal"> </span></strong>
        </p> 
                        
        
            


<br/>
    <br/>
    <div class="control-group">
        <div class="controls">    
            <button id="generar" type="submit" class="btn" disabled="disabled">Generar Ticket</button>            
        </div>
    </div>
    
</form>

<style>
    .typeahead {
        z-index: 1100;
    }
</style>

