<ul class="breadcrumb">    
    <li>
        <a href="/agenda">Ir Agenda</a> <span class="divider">/</span>
    </li>    
</ul>

<form class="form-horizontal">

    <div class="control-group">
        <label class="control-label" for="inputName">Cliente : </label>
        <div class="controls">
            <input id="clienteReserva" data-provide="typeahead" type="text" id="input" class="span5" placeholder="Ingrese Cliente">
            <span class="help-inline">
                <a href="/cliente/crear" class="btn">
                    <span class="icon-plus"></span>
                </a>
            </span>
        </div>
    </div>
    <input type="hidden" value="" id="idCliente">

    <div class="control-group">
        <label class="control-label" for="inputAtendido">Atendido por : </label>
        <div class="controls">
            <select name ="idUsuario" id="idUsuario" class="span4">
                <option>User 1</option>
            </select>
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="inputServicio">Servicio : </label>
        <div class="controls">
            <select name ="idServicio" id="idServicio" class="span3">
                <option>Servicio Uno</option>
            </select>
            <input type="text" id="precio" name="precio" placeholder="Precio Sugerido"/>
            <span class="help-inline">
                <a href="#" class="btn">
                    <span>Agregar Servicio</span>
                </a>
            </span>
        </div>
    </div>
    
    <br/>
    <br/>
    <table class="table table-condensed">
        <caption class="alert">Servicios Brindados</caption>
  <thead>
    <tr>
      <th>item</th>
      <th>Servicio</th>
      <th>Precio</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Corte</td>
      <td>10.00</td>
    </tr>
  </tbody>
</table>


<br/>
    <br/>
    <div class="control-group">
        <div class="controls">    
            <button type="submit" class="btn">Generar Ticket</button>
        </div>
    </div>
    
</form>

<style>
    .typeahead {
        z-index: 1100;
    }
</style>

<script>
    $(document).ready(function() {
        //BuscarCliente
        $('#clienteReserva').typeahead({
            source: function(typeahead, query) {
                if (query.length < 1)
                    return [];
                $.post('/agenda/listar-clientes', { query: query}, function(data) {
                    return typeahead.process(JSON.parse(data));
                });
            },
            onselect: function(obj) {
                $("#idCliente").val(obj.id);
                $("#clienteReserva").parents(".control-group").removeClass("error").addClass("success");
            }
        });

    });
</script>
