<div class="well sidebar-nav">
<ul class="nav nav-list">
    
      <li class="nav-header">Dashboard</li>
      <?php
      if($this->idTipoUsuario == 1){
      ?>
      <li class="nav-header">Mantenimientos</li>
      <li <?php echo $this->activeUsuario;?>><a href="/user/">Usuarios</a></li>
      <li <?php echo $this->activeUsuarioServicio;?>><a href="/usuario-servicio/">Estilista y Servicios</a></li>
      <li <?php echo $this->activeCliente;?>><a href="/cliente/">Clientes</a></li>
      <li <?php echo $this->activeProducto;?>><a href="/producto">Productos</a></li>
      <li <?php echo $this->activeServicio;?>><a href="/servicio">Servicios</a></li>

      <li class="nav-header">Procesos</li>
      <li <?php echo $this->activeTicket;?>><a href="/agenda">Mostrar Agenda</a></li>
      <!--<li <?php echo $this->activeListaTicket;?>><a href="#">Listar Ticket</a></li>
      <li><a href="/ticket">Tickets Atendidos</a></li>-->
      <li><a href="/ticket/nuevo">Nuevo Ticket</a></li>
      <li <?php echo $this->activePrueba;?>><a href="/reserva/">Prueba</a></li>
      
      <li class="nav-header">Reportes</li>
      <li <?php echo $this->activeReporte;?>><a href="/reporte">Reporte de Tickets</a></li>
      <li <?php echo $this->activeVentaDiaria;?>><a href="/reporte/venta-diaria">Ventas Diarias</a></li>
      <li <?php echo $this->activeReserva;?>><a href="/agenda/exportar">Exportar Reservas</a></li>
      
      
      <?php }?>
      <?php
      if($this->idTipoUsuario != 1){
      ?>
      <li class="nav-header">Procesos</li>
      <li <?php echo $this->activeTicket;?>><a href="/agenda">Mostrar Agenda</a></li>
      <!--<li <?php echo $this->activeListaTicket;?>><a href="#">Listar Ticket</a></li>
      <li><a href="/ticket">Tickets Atendidos</a></li>-->
      <li><a href="/ticket/nuevo">Nuevo Ticket</a></li>
      
      <li class="nav-header">Reportes</li>
      <li <?php echo $this->activeReporte;?>><a href="/reporte">Reporte de Tickets</a></li>
      
      <?php }?>
      
      


</ul>
</div>

