<div class="well sidebar-nav">
<ul class="nav nav-list">
    
      <li class="nav-header">Dashboard</li>
      <li class="active"><a href="#">Link</a></li>              
      <li><a href="#">Principal</a></li>
      <li><a href="#">Reporte de Tickets</a></li>
      <li><a href="#">Reporte de Productos</a></li>
      
      <li class="nav-header">Mantenimientos</li>
      <li><a href="/user/">Usuarios</a></li>
      <li><a href="/cliente/">Clientes</a></li>
      <li><a href="/producto">Productos</a></li>
      <li><a href="/servicio">Servicios</a></li>

      <li class="nav-header">Reservas</li>
      <li><a href="/agenda">Mostrar Agenda</a></li>

      <li class="nav-header">Tickets</li>
      <li><a href="/ticket">Tickets Atendidos</a></li>
      <li><a href="/ticket/nuevo">Nuevo Ticket</a></li>
</ul>
</div>

