<div class="well sidebar-nav">
<ul class="nav nav-list">
    
      <li class="nav-header">Dashboard</li>
      <li class="active"><a href="#">Link</a></li>              
      <li><a href="#">Principal</a></li>
      <li><a href="#">Reporte de Tickets</a></li>
      <li><a href="#">Reporte de Productos</a></li>
      
      <li class="nav-header">Mantenimientos</li>
      <li><a href="#">Usuario</a></li>
      <li><a href="/cliente/">Clientes</a></li>
      <li><a href="#">Productos</a></li>
      <li><a href="#">Servicios</a></li>

      <li class="nav-header">Reservas</li>
      <li><a href="#">Mostrar Agenda</a></li>

      <li class="nav-header">Tickets</li>
      <li><a href="#">Mostrar Agenda</a></li>
      <li><a href="#">Listar Ticket</a></li>
</ul>
</div>

