<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Project STYLUS</a>
          <div class="nav-collapse collapse">
            <? if($this->isAuth): ?>
                <p class="navbar-text pull-right">
                    Bienvenido
                    <a href="#"><?php echo $this->authData->nombreUsuario." ".$this->authData->apellidoUsuario;?></a>
                    <a href="/admin/auth/logout">[Cerrar Sesión]</a>
                </p>
            <? endif; ?>
            <ul class="nav">
              <li class="active"><a href="#">STYLUS</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
