

<div class="control-group">
  <label class="control-label">Cliente</label>
  <div class="controls">
    <input id="clienteReserva2" value="<?=$this->reserva[0]["nombre"]." ".$this->reserva[0]["apellidos"]?>" data-provide="typeahead" type="text" id="input" class="span12">
    <!--<span class="help-inline">
    	<a href="/cliente/crear" class="btn">
    		<span class="icon-plus"></span>
    	</a>
    </span>-->
  </div>
</div>

<div class="control-group">
  <label class="control-label" for="fechaReserva2">Fecha y Hora de Inicio:</label>
  <div class="controls">
    <input type="text" class="span4" id="fechaReserva2" >
    <span class="bootstrap-timepicker">
    	<input type="text" class="span4" id="horaReserva2" >
    </span>
  </div>
</div>

<div class="control-group">
  <label class="control-label" for="fechaReservaFin2">Fecha y Hora de Fin:</label>
  <div class="controls">
    <input type="text" class="span4" id="fechaReservaFin2" >
    <span class="bootstrap-timepicker">
    	<input type="text" class="span4" id="horaReservaFin2" >
	</span>
  </div>
</div>

<div class="control-group">
  <label class="control-label" for="descripcionReserva2">Descripción:</label>
  <div class="controls">
    <textarea rows=5 class="span12" id="descripcionReserva2"><?=$this->reserva[0]["descripcion"]?></textarea>
  </div>
</div>

<input type="hidden" value="<?=$this->start; ?>" id="fStart2">
<input type="hidden" value="<?=$this->end; ?>" id="fEnd2">
<input type="hidden" value="<?=$this->allDay; ?>" id="fAllDay2">
<input type="hidden" value="<?=$this->reserva[0]["idCliente"]; ?>" id="idCliente2">

<style>
 .typeahead {
    z-index: 1100;
}
  </style>

<script>
$(document).ready(function(){

	var fecha_ini = new Date($("#fStart2").val());
	var fecha_fin = new Date($("#fEnd2").val());
	var all_day = new Date($("#fAllDay2").val());
	
	var sFechaIni = dateHelper.dateToStr(fecha_ini, "dd/dd-mm-yyyy", "/");
	var sFechaFin = dateHelper.dateToStr(fecha_fin, "dd/dd-mm-yyyy", "/");

	var sHoraIni = dateHelper.dateToTime(fecha_ini);
	var sHoraFin = dateHelper.dateToTime(fecha_fin);

	var f1 = new Date(
		sFechaIni.split("/")[2], sFechaIni.split("/")[1], sFechaIni.split("/")[0], 0, 0, 0, 0
	);
	var f2 = new Date(
		sFechaFin.split("/")[2], sFechaFin.split("/")[1], sFechaFin.split("/")[0], 0, 0, 0, 0
	);

	//fechareserva inicial
	var checkin = $('#fechaReserva2').datepicker({
	  format: 'dd-mm-yyyy',
      todayBtn: 'linked',
      language: 'es',	
	  onRender: function(date) {
	    return date.valueOf() < f1.valueOf() ? 'disabled' : '';
	  }
	}).on('changeDate', function(ev) {
	  if (ev.date.valueOf() > checkout.date.valueOf()) {
	    var newDate = new Date(ev.date)
	    newDate.setDate(newDate.getDate());
	    checkout.setValue(newDate);
	  }
	  checkin.hide();
	  $('#fechaReservaFin2').focus();
	}).data('datepicker');

	//fechareserva final
	var checkout = $('#fechaReservaFin2').datepicker({
	  format: 'dd-mm-yyyy',
      todayBtn: 'linked',
      language: 'es',
	  onRender: function(date) {
	    return date.valueOf() <= checkin.date.valueOf() ? 'disabled' : '';
	  }
	}).on('changeDate', function(ev) {
	  checkout.hide();
	}).data('datepicker');

	//TimePicker
	$('#horaReserva2').timepicker({
		showMeridian : false,
		minuteStep   : 30,
		showSeconds  : false
	});
	$('#horaReservaFin2').timepicker({
		showMeridian : false,
		minuteStep   : 30,
		showSeconds  : false
	});

	//Fecha de Reserva
	checkin.setValue(f1);
	checkout.setValue(f2);

	//Hora de Reserva
	$('#horaReserva2').timepicker('setTime', sHoraIni);
	$('#horaReservaFin2').timepicker('setTime', sHoraFin);

	//BuscarCliente
	$('#clienteReserva2').typeahead({
	    source: function (typeahead, query) {
	        if (query.length<1) return [];
	        $.post('/agenda/listar-clientes', { query: query }, function (data) {
	            return typeahead.process(JSON.parse(data));
	        });
	    },
	    onselect: function (obj) {
	    	$("#idCliente2").val(obj.id);
	    	$("#clienteReserva2").parents(".control-group").removeClass("error").addClass("success");
	    }
	});

});
</script>