<h2> AGENDA </h2>
<hr />
<script type='text/javascript'>

	$(document).ready(function() {
	
		

		var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
		
		$('#calendar').fullCalendar({
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
			selectable: true,
			editable: true,
			select: function(start, end, allDay) {

				/*var title = prompt('Event Title:');
				if (title) {
					calendar.fullCalendar('renderEvent',
						{
							title: title,
							start: start,
							end: end,
							allDay: allDay
						},
						true // make the event "stick"
					);
				}*/
				$("#modalReserva").modal({
							keyboard : true,
							backdrop : true,
							show : true
				});

				$("#contentReserva .contenido").removeClass("hide");
				$("#contentReserva .loading").removeAttr("style");
				$("#contentReserva .loading").addClass("hide");
				
				$("#contentReserva .contenido").html("");
				$("#contentReserva .contenido").addClass("loading");

				var datos = {
					start : start,
					end   : end,
					allDay : allDay
				};

				$.ajax({
                       url: "/agenda/nueva-reserva",
                       type: 'post',
                       data: datos,
                       dataType: 'html',
                       success: function(response) {
                       		$("#contentReserva .contenido").removeClass("loading");
                       		$("#contentReserva .contenido").html(response);
                       }
                 });

				//calendar.fullCalendar('unselect');
			},
			eventClick: function(calEvent, jsEvent, view) {
				$("#modalEliminarReserva").modal({
							keyboard : true,
							backdrop : true,
							show : true
				});

				var titulo = calEvent.title;
				var id = titulo.split("|");
				$("#idReserva").val(id[0]);
				//$("#btnGenerarTicket").attr("href", "/ticket/nuevo/id/"+$("#idCliente2").val());


				$("#contentEliminarReserva .contenido").html("");
				$("#contentEliminarReserva .contenido").addClass("loading");

				var datos = {
					idreserva : id[0]
				}

				$.ajax({
                       url: "/agenda/editar-reserva",
                       type: 'post',
                       data: datos,
                       dataType: 'html',
                       success: function(response) {
                       		$("#contentEliminarReserva .contenido").removeClass("loading");
                       		$("#contentEliminarReserva .contenido").html(response);
                       		$("#btnGenerarTicket").attr("href", "/ticket/nuevo/id/"+$("#idCliente2").val());
                       	
                       		var datec = new Date(calEvent.start);
                       		var x1 = datec.getDate()+"/"+datec.getMonth()+"/"+datec.getFullYear();
                       		var x2 = date.getDate()+"/"+date.getMonth()+"/"+date.getFullYear();
                       		
                       		if (x1!=x2) {
                       			$("#btnGenerarTicket").addClass("hide");
                       		} else {
                       			$("#btnGenerarTicket").removeClass("hide");
                       		}
                       }
                 });
					
				
		    },
			events: <?=$this->reservas?>
		});

	//Formulario registro
	$("#btnGuardarReserva").live("click",function() {
		var fecha_reserva_ini = $("#fechaReserva").val();
		var hora_reserva_ini = $("#horaReserva").val();

		var fecha_reserva_fin = $("#fechaReservaFin").val();
		var hora_reserva_fin = $("#horaReservaFin").val();
        
        var idestilista = $("#idestilista").val();

		var descripcion = $("#descripcionReserva").val();
		var idcliente = $("#idCliente").val();

		if (idcliente == "") {
			$("#clienteReserva").parents(".control-group").addClass("error");
		} else {
			var datos = {
				fecha_reserva_ini : fecha_reserva_ini,
				hora_reserva_ini  : hora_reserva_ini,
				fecha_reserva_fin : fecha_reserva_fin,
				hora_reserva_fin  : hora_reserva_fin,
				descripcion       : descripcion,
				idcliente         : idcliente,
                idestilista       : idestilista
			};

			$("#contentReserva .contenido").addClass("hide");
			$("#contentReserva .loading").removeClass("hide");
			$("#contentReserva .loading").attr("style","height:100px");


			$.ajax({
	               url: "/agenda/registrar-reserva",
	               type: 'post',
	               data: datos,
	               dataType: 'json',
	               success: function(response) {
	               		if (response.status = false) {
	               			$("#contentReserva .contenido").removeClass("hide");
	               			$("#contentReserva .loading").addClass("hide");
	               			$("#contentReserva .loading").removeAttr("style");
	               			
	               		} else {
	               			location.href = urls.siteUrl + response.url;
	               		}
	               }
	         });
		}
	});

	$("#clienteReserva").live("change", function(){
		$(this).parents(".control-group").removeClass("success").addClass("error");
		$("#idCliente").val("");
	});



	//Eliminar
	$("#btnEliminarReserva").live("click", function(){
		$("#modalEliminarReserva").find("form").submit();
	});



		
});

</script>
<style type='text/css'>
	#calendar {
		width: auto;
		margin: 0 auto;
		}
</style>


<!-- CALENDARIO -->
<div id='calendar'></div>


<!-- FORMULARIO -->
<div id="modalReserva" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Nueva Reserva</h3>
  </div>
  <div class="modal-body" id="contentReserva" style="max-height: 620px">
  	<div class="loading hide"></div>
  	<div class="contenido"></div>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" onClick="$('#modalReserva .close').click()">Cerrar</a>
    <a id="btnGuardarReserva" href="#" class="btn btn-primary">Guardar</a>
  </div>
</div>

<!-- ELIMINAR EVENTO -->
<div id="modalEliminarReserva" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Editar Reserva</h3>
  </div>
  <div class="modal-body" id="contentEliminarReserva" style="max-height: 620px">
  	<div class="contenido">
  	</div>
  	 <form action="/agenda/eliminar-reserva" method="post">
  		<input type="hidden" name="idReserva" id="idReserva" />
     </form>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" onClick="$('#modalEliminarReserva .close').click()">Cancelar</a>
    <a id="btnEliminarReserva" href="#" class="btn btn-primary">Eliminar</a>

    <a id="btnGenerarTicket" href="#" class="btn btn-success" style="float:left">Generar Ticket</a>
  </div>
</div>
