<!doctype html>
<html>
<head>
    <meta charset="utf-8">    
    <link href="<?php echo SITE_URL ?>static/css/styles/admin.css?201303102350" media="all" rel="stylesheet" type="text/css" >
    
    <title>Coupon</title>
    <style type="text/css" media="all">
        body {font-family: Helvetica;font-size: 15px}
        @page { margin: 0.3in 0.3in 0.3in 0.3in;}
    </style>
    <script type="text/javascript" src="<?php echo MEDIA_URL?>/js/libs/jquery-1.7.1.min.js"></script>
</head>
<body>
<h3> Reporte de Reserva </h3>
<h4> del <?php echo $this->fechai . " al " . $this->fechaf; ?> </h4>
<br />
    <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Cliente</th>
                  <th>Fecha Inicio</th>
                  <th>Fecha Fin</th>                  
                  <th>Estilista</th>                  
                  <th>Usuario Reg.</th>
                </tr>
              </thead>
              <tbody>
                  <?php foreach ($this->pdf as$item): ?>
                <tr>
                  <td><?php echo $item['nombre']." ". $item['apellidos']?></td>
                  <td><?php echo $item['fechaIni']?></td>
                  <td><?php echo $item['fechaFin']?></td>                  
                  <td><?php echo $item['nombree']." ". $item['apellidoe']?></td>
                  <td><?php echo $item['nombreu']." ". $item['apellidou']?></td>
                </tr>
                <?php endforeach; ?>
              </tbody>
            </table>
    
</body>
</html>
