  <div>
        <!-- row of columns -->
        <div class="row-fluid">
          
          <div>
                <ul class="breadcrumb">                    
                    <li><a href="#">Consultar Reservas por fecha</a></li>
                </ul>
              <form class="well inline" method="post" enctype="multipart/form-data" >
                      <h3>Buscar Reserva</h3>
                      <hr>                      
                      <div class="row-fluid">
                          <div class="span4">
                              <h4>Fecha Inicial:</h4>
                              <?php echo $this->form->fechaInicial;?>
                           </div>
                          <div class="span4">
                              <h4>Fecha Final:</h4>
                              <?php echo $this->form->fechaFinal;?>
                           </div>
                                    
                          <div class="span1">
                              <?php echo $this->form->buscar?>
                           </div>
                      </div>
                 </form>
                 <div id="message"></div>
                 <!--<table class="table table-bordered">                     
                   <thead>
                     <tr>                       
                       <th>
                           Nro. Ticket
                       </th>
                       <th>
                           Tipo Usuario
                       </th>
                       <th>
                           Nombre Usuario
                       </th>
                       <th>
                           Cliente
                       </th>
                       <th>
                           Fecha Creacion
                       </th>
                       <th>
                           Total
                       </th>
                     </tr>
                   </thead>
                  <!-- <tbody>
                     <?php /*
                     foreach ($this->result as $res):?>
                     <tr>
                      <td>
                         <?php echo $res["idServicio"]; ?>
                       </td>
                       <td>
                         <?php echo $res["descripcionServicio"]; ?>
                       </td>
                       <td>
                         <?php echo $res["precio"]; ?>
                       </td>
                       <td>
                         <?php echo $res["precio"]; ?>
                       </td>
                       <td>
                         <?php echo $res["precio"]; ?>
                       </td>
                       <td>
                         <?php if($res["idTipoMoneda"]==1){
                             echo "Soles";
                         }else{echo "Dolar";} ?>
                       </td>
                       <td>
                           <a href="/admin/servicio/editar/id/<?php echo $res["idServicio"]; ?>" title="Editar">Editar</a> |
                           <a href="/admin/servicio/eliminar/id/<?php echo $res["idServicio"]; ?>" title="Editar">Eliminar</a>
                       </td>
                     </tr>
                         <?php endforeach; */?>
                   </tbody>
                 </table>-->
         </div>
        </div>                
  </div>
<script>
$(document).ready(function(){
    $('#fechaInicial').datepicker({
        format: 'yyyy-mm-dd',
        todayBtn: 'linked',
        language: 'es'
    });
    
     $('#fechaFinal').datepicker({
        format: 'yyyy-mm-dd',
        todayBtn: 'linked',
        language: 'es'
    });
});
</script>