<ul class="breadcrumb">    
    <li>
        <a href="/usuario-servicio">Usuarios por Servicio</a> <span class="divider">/</span>
    </li>    
</ul>
<div id="content_wrapper">
     <div id="content">
         <div class="inner">
             <form action="" method="post" enctype="multipart/form-data" class="well">
                <div class="header">
                    <h3>Registrar Servicio para el Usuario:</h3>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        <div class="clear"></div>
                        <div class="span8"></div>
                        <label for="nombre" class="span5 no-margin">Usuario :</label>
                        <div class="span7 no-margin">
                            <?php echo $this->form->idUsuario->setAttrib('class', 'span12')->setAttrib('maxlength', '50')->renderViewHelper();?>
                            <?php if ($this->form->idUsuario->hasErrors()) echo "Seleccione Usuario";?>
                        </div>
                        <div class="clear"></div>
                        <label for="apellido" class="span5 no-margin">Servicio :</label>
                        <div class="span7 no-margin">
                            <?php echo $this->form->idServicio->setAttrib('class', 'span12')->setAttrib('maxlength', '50')->renderViewHelper();?>
                            <?php if ($this->form->idServicio->hasErrors()) echo "Seleccione Servicio";?>
                        </div>
                        <div class="clear"></div>
                        <label for="dni" class="span5 no-margin">Comision :</label>
                        <div class="span4 no-margin">
                            <?php echo $this->form->comision->setAttrib('class', 'span12')->setAttrib('maxlength', '8')->renderViewHelper();?>
                            <?php if ($this->form->comision->hasErrors()) echo "Ingresa Comision";?> 
                        </div>&nbsp; %
                        <div class="clear"></div>
                        
                        <?php echo $this->form->csrf; ?>
                    </div>
                    <div class="clear"></div>
                                        
                </div>
                <div class="form-actions">
                    <?php echo $this->form->guardar->setAttrib('class', 'btn pull-right')?>                    
                </div>
        </form>
    </div>
 </div>
</div>
